urls.py
from django.views.generic.base import RedirectView
from django.urls import path, reverse_lazy
from . import views

app_name = "libtekin"

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("libtekin:item-list"))),
    path("item/", RedirectView.as_view(url=reverse_lazy("libtekin:item-list"))),
    path("item/create/", views.ItemCreate.as_view(), name="item-create"),
    path("item/<int:pk>/update/", views.ItemUpdate.as_view(), name="item-update"),
    path("item/<int:pk>/detail/", views.ItemDetail.as_view(), name="item-detail"),
    path("item/<int:pk>/delete/", views.ItemSoftDelete.as_view(), name="item-delete"),
    path(
        "item/list/filterstore/<int:from_store>/",
        views.ItemList.as_view(),
        name="item-filterstore",
    ),
    path(
        "item/list/",
        views.ItemList.as_view(),
        name="item-list",
    ),
    path("item/<int:pk>/copy/", views.ItemCopy.as_view(), name="item-copy"),
    path(
        "item/<str:copied_from>/copied/", views.ItemList.as_view(), name="item-copied"
    ),
    path(
        "item/csv/",
        views.ItemCSV.as_view(),
        name="item-csv",
    ),
    path(
        "primary_id_count/<str:primary_id>/",
        views.count_primary_id,
        name="primary-id-count",
    ),
    path(
        "primary_id_count/<pk>/<str:primary_id>/",
        views.count_primary_id,
        name="primary-id-count",
    ),
    path("entity/", RedirectView.as_view(url=reverse_lazy("libtekin:entity-list"))),
    path("entity/create/", views.EntityCreate.as_view(), name="entity-create"),
    path("entity/popup/", views.EntityCreate.as_view(), name="entity-popup"),
    path("entity/<int:pk>/update/", views.EntityUpdate.as_view(), name="entity-update"),
    path("entity/<int:pk>/detail/", views.EntityDetail.as_view(), name="entity-detail"),
    path("entity/<int:pk>/delete/", views.EntityDelete.as_view(), name="entity-delete"),
    path("entity/list/", views.EntityList.as_view(), name="entity-list"),
    path("location/", RedirectView.as_view(url=reverse_lazy("libtekin:location-list"))),
    path("location/create/", views.LocationCreate.as_view(), name="location-create"),
    path("location/popup/", views.LocationCreate.as_view(), name="location-popup"),
    path(
        "location/<int:pk>/update/",
        views.LocationUpdate.as_view(),
        name="location-update",
    ),
    path(
        "location/<int:pk>/detail/",
        views.LocationDetail.as_view(),
        name="location-detail",
    ),
    path(
        "location/<int:pk>/delete/",
        views.LocationDelete.as_view(),
        name="location-delete",
    ),
    path("location/list/", views.LocationList.as_view(), name="location-list"),
    path("mmodel/", RedirectView.as_view(url=reverse_lazy("libtekin:mmodel-list"))),
    path("mmodel/create/", views.MmodelCreate.as_view(), name="mmodel-create"),
    path("mmodel/popup/", views.MmodelCreate.as_view(), name="mmodel-popup"),
    path("mmodel/<int:pk>/update/", views.MmodelUpdate.as_view(), name="mmodel-update"),
    path("mmodel/<int:pk>/detail/", views.MmodelDetail.as_view(), name="mmodel-detail"),
    path("mmodel/<int:pk>/delete/", views.MmodelDelete.as_view(), name="mmodel-delete"),
    path("mmodel/list/", views.MmodelList.as_view(), name="mmodel-list"),
    path("mmodel/<int:pk>/close/", views.MmodelClose.as_view(), name="mmodel-close"),
    path(
        "mmodelcategory/create/",
        views.MmodelCategoryCreate.as_view(),
        name="mmodelcategory-create",
    ),
    path(
        "mmodelcategory/popup/",
        views.MmodelCategoryCreate.as_view(),
        name="mmodelcategory-popup",
    ),
    path(
        "mmodelcategory/<int:pk>/update/",
        views.MmodelCategoryUpdate.as_view(),
        name="mmodelcategory-update",
    ),
    path(
        "mmodelcategory/<int:pk>/detail/",
        views.MmodelCategoryDetail.as_view(),
        name="mmodelcategory-detail",
    ),
    path(
        "mmodelcategory/<int:pk>/delete/",
        views.MmodelCategoryDelete.as_view(),
        name="mmodelcategory-delete",
    ),
    path(
        "mmodelcategory/list/",
        views.MmodelCategoryList.as_view(),
        name="mmodelcategory-list",
    ),
    path(
        "mmodel/<int:pk>/primary_id_field/",
        views.get_primary_id_field,
        name="get_primary_id_field",
    ),
    path("itemnote/", RedirectView.as_view(url=reverse_lazy("libtekin:itemnote-list"))),
    path("itemnote/create/", views.ItemNoteCreate.as_view(), name="itemnote-create"),
    path("itemnote/popup/", views.ItemNoteCreate.as_view(), name="itemnote-popup"),
    path(
        "itemnote/<int:pk>/update/",
        views.ItemNoteUpdate.as_view(),
        name="itemnote-update",
    ),
    path(
        "itemnote/<int:pk>/detail/",
        views.ItemNoteDetail.as_view(),
        name="itemnote-detail",
    ),
    path(
        "itemnote/<int:pk>/delete/",
        views.ItemNoteDelete.as_view(),
        name="itemnote-delete",
    ),
    path("itemnote/list/", views.ItemNoteList.as_view(), name="itemnote-list"),
    path(
        "itemnotecategory/create/",
        views.ItemNoteCategoryCreate.as_view(),
        name="itemnotecategory-create",
    ),
    path(
        "itemnotecategory/popup/",
        views.ItemNoteCategoryCreate.as_view(),
        name="itemnotecategory-popup",
    ),
    path(
        "itemnotecategory/<int:pk>/update/",
        views.ItemNoteCategoryUpdate.as_view(),
        name="itemnotecategory-update",
    ),
    path(
        "itemnotecategory/<int:pk>/detail/",
        views.ItemNoteCategoryDetail.as_view(),
        name="itemnotecategory-detail",
    ),
    path(
        "itemnotecategory/<int:pk>/delete/",
        views.ItemNoteCategoryDelete.as_view(),
        name="itemnotecategory-delete",
    ),
    path(
        "itemnotecategory/list/",
        views.ItemNoteCategoryList.as_view(),
        name="itemnotecategory-list",
    ),
    path(
        "member/popup/",
        views.MemberCreate.as_view(),
        name="member-popup",
    ),
]

models.py
from datetime import date, datetime, timedelta
from django.utils import timezone

from django.apps import apps
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core import exceptions
from django.db import models
from django.db.models import Count, OuterRef, Q, Subquery
from django.db.models.functions import Concat
from django.urls import reverse
from spl_members.models import Member


def get_default_status():
    try:
        return Status.objects.filter(is_default=True).first().pk
    except AttributeError:
        return None


def get_default_level():
    try:
        return ItemNoteLevel.objects.filter(number=0).first().pk
    except AttributeError:
        return None


class EntityCategory(models.Model):
    name = models.CharField(
        "name",
        max_length=75,
        help_text='The name of the entity category, like "Person" or "Organization"',
    )
    sort_name = models.CharField(
        "sort name",
        max_length=25,
        blank=True,
        help_text='A name for sorting, not normally displayed.  This can be as simple as "A","B", or "C", or something like "C Organization"',
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["sort_name", "name"]


class Entity(models.Model):
    friendly_name = models.CharField(
        "friendly name",
        max_length=25,
        blank=True,
        help_text='The friendly name for this person or organization, like "Ben" or "IT"',
    )
    full_name = models.CharField(
        "full name",
        max_length=75,
        help_text='The full name for this person or organization, like "Benjamin Goldberg" or "Suffolk Information Technology Division"',
    )
    category = models.ForeignKey(
        EntityCategory,
        on_delete=models.SET_NULL,
        null=True,
        help_text="The type of entity",
    )

    def __str__(self):
        return self.full_name

    class Meta:
        ordering = ["full_name"]


class LocationCategory(models.Model):
    name = models.CharField(
        "name",
        max_length=75,
        help_text='The name of the location category, like "Library Location"',
    )
    sort_name = models.CharField(
        "sort name",
        max_length=25,
        blank=True,
        help_text='A name for sorting, not normally displayed.  This can be as simple as "A","B", or "C", or something like "B Library Location"',
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["sort_name", "name"]


class Location(models.Model):
    short_name = models.CharField(
        "short name",
        max_length=25,
        blank=True,
        help_text='The short name for this location, like "MML"',
    )
    full_name = models.CharField(
        "full name",
        max_length=75,
        help_text='The full name for this location, like "Morgan Memorial Library',
    )
    category = models.ForeignKey(
        LocationCategory,
        verbose_name="category",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="The category of this location",
    )

    def __str__(self):
        return self.full_name

    class Meta:
        ordering = ["full_name"]


class MmodelCategory(models.Model):
    name = models.CharField(
        "name",
        max_length=75,
        help_text='The name of the category, like "Laptop Computer"',
    )
    sort_name = models.CharField(
        "sort name",
        max_length=25,
        blank=True,
        help_text='A name for sorting, not normally displayed.  This can be as simple as "A","B", or "C", or something like "B Laptops"',
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["sort_name"]


class Mmodel(models.Model):
    ID_CHOICES = [
        ("serial_number", "Serial Number"),
        ("bios_serial_number", "Bios Serial Number"),
        ("asset_number", "Asset Number"),
        ("barcode", "Barcode"),
    ]

    brand = models.CharField(
        "brand",
        max_length=75,
        help_text="The brand name of the item or the manufacturer, or supplier, etc..",
    )
    model_name = models.CharField(
        "model_name", max_length=75, help_text='The model name, like "Latitude 3390"'
    )
    model_number = models.CharField(
        "model_number",
        max_length=75,
        blank=True,
        help_text="The model number if different than model name",
    )
    category = models.ForeignKey(
        MmodelCategory,
        verbose_name="category",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="The category, such as Laptop or Phone, to which this item belongs",
    )
    primary_id_field = models.CharField(
        "Primary ID Field",
        max_length=50,
        blank=True,
        help_text='By default, the field which should be used as the primary ID field (ex: "SN", "Tag Number", etc)',
    )

    def __str__(self):
        return f"{self.brand} {self.model_name}"

    class Meta:
        ordering = ["brand", "model_name"]
        verbose_name = "model"


class Role(models.Model):
    name = models.CharField(
        "name", max_length=75, help_text='The name of the role ("Public", "Staff", etc)'
    )
    sort_name = models.CharField(
        "sort name",
        max_length=25,
        blank=True,
        help_text='A name for sorting, not normally displayed.  This can be as simple as "A","B", or "C", or something like "B Public"',
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["sort_name", "name"]


class Status(models.Model):
    name = models.CharField(max_length=50, help_text="The status of the item")
    list_position = models.IntegerField(
        "rank",
        default=1000,
        help_text="The order that this status should display in a list of statuses",
    )
    is_active = models.BooleanField(
        "is active", default=False, help_text="If this status is for an active item)"
    )
    is_default = models.BooleanField(
        "is default",
        default=False,
        help_text="If this is the default status for new items (Only one will used even if more than one is selected)",
    )

    class Meta:
        ordering = (
            "list_position",
            "name",
        )

    def __str__(self):
        return self.name


class ItemNotDeletedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


class ItemAllManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()


class Item(models.Model):
    common_name = models.CharField(
        "common name",
        max_length=75,
        blank=True,
        help_text='The common name for this piece of equipment, like "Ben\'s Laptop"',
    )
    mmodel = models.ForeignKey(
        Mmodel,
        verbose_name="model",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="The items model",
    )
    primary_id = models.CharField(
        "primary ID",
        max_length=100,
        blank=True,
        help_text="The primary ID used for this item",
    )
    primary_id_field = models.CharField(
        "primary id field",
        max_length=50,
        blank=True,
        help_text="The identifier which is the primary id",
    )
    network_name = models.CharField(
        "network name", max_length=100, blank=True, help_text="The item's network name"
    )
    serial_number = models.CharField(
        "serial number",
        max_length=100,
        blank=True,
        help_text="The serial number or alternate ID which is used as the serial number",
    )
    bios_serial_number = models.CharField(
        "bios serial number",
        max_length=100,
        blank=True,
        help_text="The serial number stored in bios used by several computer manufacturers",
    )
    asset_number = models.CharField(
        "asset number",
        max_length=100,
        blank=True,
        help_text="The local inventory number for this item",
    )
    barcode = models.CharField(
        "barcode",
        max_length=100,
        blank=True,
        help_text="The barcode attached to this item",
    )
    phone_number = models.CharField(
        "phone_number",
        max_length=100,
        blank=True,
        help_text="The phone number of the device",
    )
    mobile_id = models.CharField(
        "Mobile ID",
        max_length=100,
        blank=True,
        help_text="The device's IMEI, MEID, SSID, etc..",
    )
    sim_iccid = models.CharField(
        "SIM iccid", max_length=100, blank=True, help_text="The id of the SIM card"
    )
    owner = models.ForeignKey(
        Entity,
        verbose_name="owner",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="item_owned",
        help_text="The owner of the item",
    )
    assignee = models.ForeignKey(
        Member,
        verbose_name="member assignee",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="item_assigned_to_member",
        help_text="The responsible party for the item",
    )
    borrower = models.ForeignKey(
        Member,
        verbose_name="member borrower",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="item_borrowed_to_member",
        help_text="The temporary user of the item",
    )

    home = models.ForeignKey(
        Location,
        verbose_name="home",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="item_homed",
        help_text="The home location of this item",
    )
    location = models.ForeignKey(
        Location,
        verbose_name="location",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="item_located",

templates/libtekin/_app_menu.html
<div class="menu app-menu">

  {% if perms.libtekin.view_item %}
    {% if 'item-' in request.resolver_match.url_name %}
      <div class="menu-item menu-here">
        <a href="{% url 'libtekin:item-list' %}">Items</a>
      </div>
    {% else %}
      <div class="menu-item">
        <a href="{% url 'libtekin:item-list' %}">Items</a>
      </div>
    {% endif %}
  {% endif %}
{% if perms.libtekin.view_mmodel %}
  {% if 'mmodel' in request.resolver_match.url_name %}
  <div class="menu-item menu-here">
        <a href="{% url 'libtekin:mmodel-list' %}">Models</a>
      </div>
    {% else %}
      <div class="menu-item">
        <a href="{% url 'libtekin:mmodel-list' %}">Models</a>
      </div>
      {% endif %}
    {% endif %}
  {% if perms.libtekin.view_itemnote %}
    {% if 'itemnote' in request.resolver_match.url_name %}
      <div class="menu-item menu-here">
        <a href="{% url 'libtekin:itemnote-list' %}">Item Notes</a>
      </div>
    {% else %}
      <div class="menu-item">
        <a href="{% url 'libtekin:itemnote-list' %}">Item Notes</a>
      </div>
    {% endif %}
  {% endif %}

</div>

templates/libtekin/_form_field.html
<div class="field-wrapper">
  {% if field.errors %}
    <div class="errors">
      {{ field.errors }}
    </div>
  {% endif %}
  <div class="control">
    <div class="label">
      {% if label_tag %}
        {{ label_tag }}
      {% else %}
        {{ field.label_tag }}
      {% endif %}
    </div>
    <div class="field">
      {{ field }} {{ extra }}
    </div>
  </div>
  <div class="help_text">
    {% if help_text %}
      {{ help_text }}
    {% else %}
     {{ field.help_text}}
    {% endif %}
  </div>
</div>

templates/libtekin/_form_field_old.html
<div class="field-wrapper">
  {% if field.errors %}
    <div class="errors">
      {{ field.errors }}
    </div>
  {% endif %}
  <div class="control">
    <div class="label">
      {{ field.label_tag }}
    </div>
    <div class="field">
      {{ field }}
    </div>
  </div>
  <div class="help_text">
    {{ field.help_text}}
  </div>
</div>

templates/libtekin/item_list.html
{% extends './_base.html' %}
{% load static %}
{% block content %}

{% include 'tougshire_vistas/filter.html' %}

<div class="list">
    <div><a href="{% url 'libtekin:item-create' %}">create</a></div>
    <div><a href="{% url 'libtekin:item-csv' %}">export</a></div>
      <div class="row rowhead">
        {% include './_list_head.html' with field='' %}
        {% if 'common_name' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.common_name %}
        {% endif %}
        {% if 'mmodel' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.mmodel %}
        {% endif %}
        {% if 'primary_id' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.primary_id %}
        {% endif %}
        {% if 'serial_number' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.serial_number %}
        {% endif %}
        {% if 'service_number' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.service_number %}
        {% endif %}
        {% if 'asset_number' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.asset_number %}
        {% endif %}
        {% if 'barcode' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.barcode %}
        {% endif %}
        {% if 'network_name' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.network_name %}
        {% endif %}
        {% if 'phone_number' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.phone_number %}
        {% endif %}
        {% if 'mobile_id' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.mobile_id %}
        {% endif %}
        {% if 'sim_iccid' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.sim_iccid %}
        {% endif %}

        {% if 'role' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.role %}
        {% endif %}
        {% if 'connected_to' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.connected_to %}
        {% endif %}
        {% if 'status' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.status %}
        {% endif %}
        {% if 'home' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.home %}
        {% endif %}
        {% if 'location' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.location %}
        {% endif %}
        {% if 'assignee' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.assignee %}
        {% endif %}
        {% if 'borrower' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.borrower %}
        {% endif %}
        {% if 'owner' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.owner %}
        {% endif %}
        {% if 'latest_inventory' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.latest_inventory %}
        {% endif %}
        {% if 'installation_date' in show_columns or not show_columns %}
          {% include './_list_head.html' with field=labels.installation_date %}
        {% endif %}

      </div>

      {% for item in object_list %}
        <div class="row">
          <div class="listfield"><a href="{% url 'libtekin:item-detail' item.pk %}">view</a></div>
          <div class="listfield"><a href="{% url 'libtekin:item-update' item.pk %}">edit</a></div>
          {% if 'common_name' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.common_name %}
          {% endif %}
          {% if 'mmodel' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.mmodel %}
          {% endif %}
          {% if 'primary_id' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.primary_id %}
          {% endif %}
          {% if 'serial_number' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.serial_number %}
          {% endif %}
          {% if 'service_number' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.service_number %}
          {% endif %}
          {% if 'asset_number' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.asset_number %}
          {% endif %}
          {% if 'barcode' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.barcode %}
          {% endif %}
          {% if 'network_name' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.network_name %}
          {% endif %}
          {% if 'phone_number' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.phone_number %}
          {% endif %}
          {% if 'mobile_id' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.mobile_id %}
          {% endif %}
          {% if 'sim_iccid' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.sim_iccid %}
          {% endif %}

          {% if 'role' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.role %}
          {% endif %}
          {% if 'connected_to' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.connected_to %}
          {% endif %}
          {% if 'status' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.status %}
          {% endif %}
          {% if 'home' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.home.short_name %}
          {% endif %}
          {% if 'location' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.location.short_name %}
          {% endif %}
          {% if 'assignee' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.assignee.friendly_name %}
          {% endif %}
          {% if 'borrower' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.borrower.friendly_name %}
          {% endif %}
          {% if 'owner' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.owner.friendly_name %}
          {% endif %}
          {% if 'latest_inventory' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.latest_inventory %}
          {% endif %}
          {% if 'installation_date' in show_columns or not show_columns %}
            {% include './_list_field.html' with field=item.installation_date %}
          {% endif %}

        </div>
      {% endfor %}
      <div>Count: {{ count }}</div>

    </div>
  </div>
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a id="a_first" href="?page=1">&laquo; first</a>
            <a id="a_previous" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a id="a_next" href="?page={{ page_obj.next_page_number }}">next</a>
            <a id="a_last" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>

{% endblock %}
{% block bottomscript %}
  {{ block.super }}

  <script>

    for( paginator of ['a_first', 'a_previous', 'a_next', 'a_last']) {
      if(!(document.getElementById(paginator)==null) ) {
        document.getElementById(paginator).addEventListener('click', function(e) {
          e.preventDefault()
          document.getElementById('frm_vista').action = e.target.href
          document.getElementById('frm_vista').submit()
        });
      }
    }
  </script>

{% endblock %}

templates/libtekin/itemnote_list.html
{% extends './_base.html' %}
{% load static %}
{% block content %}

<div class="list">
  <div><a href="{% url 'libtekin:itemnote-create' %}">create</a></div>
    <div class="row rowhead">
        {% include 'touglates/list_head.html' with field='' %}
        {% if 'item' in show_columns or not show_columns %}
          {% include 'touglates/list_head.html' with field=labels.item %}
        {% endif %}
        {% if 'level' in show_columns or not show_columns %}
          {% include 'touglates/list_head.html' with field=labels.level %}
        {% endif %}
        {% if 'flagged' in show_columns or not show_columns %}
          {% include 'touglates/list_head.html' with field=labels.flagged %}
        {% endif %}

        {% if 'when' in show_columns or not show_columns %}
          {% include 'touglates/list_head.html' with field=labels.when %}
        {% endif %}
        {% if 'itemnotecategory' in show_columns or not show_columns %}
          {% include 'touglates/list_head.html' with field=labels.itemnotecategory %}
        {% endif %}
        {% if 'maintext' in show_columns or not show_columns %}
          {% include 'touglates/list_head.html' with field=labels.maintext %}
        {% endif %}
        {% if 'details' in show_columns or not show_columns %}
          {% include 'touglates/list_head.html' with field=labels.details %}
        {% endif %}

      </div>

      {% for itemnote in object_list %}
        <div class="row">
          <div class="listfield"><a href="{% url 'libtekin:itemnote-detail' itemnote.pk %}">view</a></div>
          <div class="listfield"><a href="{% url 'libtekin:itemnote-update' itemnote.pk %}">edit</a></div>
          {% if 'item' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=itemnote.item %}
          {% endif %}
          {% if 'level' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=itemnote.level %}
          {% endif %}
          {% if 'flagged' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=itemnote.flagged %}
          {% endif %}

          {% if 'when' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=itemnote.when %}
          {% endif %}
          {% if 'itemnotecategory' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=itemnote.itemnotecategory %}
          {% endif %}
          {% if 'maintext' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=itemnote.maintext %}
          {% endif %}
          {% if 'details' in show_columns or not show_columns %}
            {% include 'touglates/list_field.html' with field=itemnote.details %}
          {% endif %}

        </div>
      {% endfor %}
      <div>Count: {{ count }}</div>

    </div>
  </div>
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a id="a_first" href="?page=1">&laquo; first</a>
            <a id="a_previous" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a id="a_next" href="?page={{ page_obj.next_page_number }}">next</a>
            <a id="a_last" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>

{% endblock %}
{% block bottomscript %}
  {{ block.super }}
{% endblock %}